### ISSUE TITLE
ImportError: cannot import name 'token_urlsafe' from 'secrets'

### ISSUE THREAD

**Issue by AwesomeShare** [samirelanduk/reddit-save#7]
I am having trouble running the script.  Would you please help me diagnose the issue?

I created the "secrets.py" file and fill in all my information (REDDIT_USERNAME, REDDIT_PASSWORD, REDDIT_CLIENT_ID, and REDDIT_SECRET that I generated under the reddit API section on their website.

    $ ./save.py saved SavedFolder
Traceback (most recent call last):
  File "./save.py", line 7, in <module>
    from utilities import *
  File "C:\Users\SP\reddit-save\utilities.py", line 4, in <module>
    from redvid import Downloader
  File "C:\Users\SP\AppData\Local\Programs\Python\Python38-32\lib\site-packages\redvid\__init__.py", line 1, in <module>
    from .redvid import Downloader
  File "C:\Users\SP\AppData\Local\Programs\Python\Python38-32\lib\site-packages\redvid\redvid.py", line 1, in <module>
    from secrets import token_urlsafe
ImportError: cannot import name 'token_urlsafe' from 'secrets' (C:\Users\SP\reddit-save\secrets.py)

**Comment by samirelanduk** [comment]
Looms like the `redvid` package's latest release now imports from a package called `secrets` which clashes with the local file of the same name. Try running `pip install redvid==1.1.3` and then running again.

I should probably change the name of the secrets file though too, as it clases with an established package name.
